// mongo-init/seed.js
// Runs automatically on first container startup via Docker entrypoint.
// Creates the employees collection and seeds 12 realistic records.

db = db.getSiblingDB("employee_directory");

db.createCollection("employees");
db.employees.createIndex({ email: 1 }, { unique: true });
db.employees.createIndex({ department: 1 });
db.employees.createIndex({ employmentStatus: 1 });
db.employees.createIndex({ lastName: 1, firstName: 1 });
db.employees.createIndex(
  { firstName: "text", lastName: "text", email: "text", designation: "text" },
  { name: "employee_text_search" }
);

const now = new Date();

db.employees.insertMany([
  {
    firstName: "Thava",
    lastName: "Gopal",
    email: "thava.gopal@company.com",
    phone: "+1-416-555-0192",
    designation: "Senior QA Engineer",
    department: "QA",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2022-03-15"),
    address: { street: "123 Innovation Drive", city: "Toronto", state: "Ontario", postalCode: "M5V 3A8", country: "Canada" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Priya",
    lastName: "Ramachandran",
    email: "priya.ramachandran@company.com",
    phone: "+1-604-555-0147",
    designation: "Lead Software Engineer",
    department: "Engineering",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2020-07-01"),
    address: { street: "45 Harbour Centre", city: "Vancouver", state: "British Columbia", postalCode: "V6Z 2E1", country: "Canada" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "James",
    lastName: "O'Sullivan",
    email: "james.osullivan@company.com",
    phone: "+44-20-7946-0958",
    designation: "Product Manager",
    department: "Product",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2021-01-11"),
    address: { street: "10 Canary Wharf", city: "London", state: "England", postalCode: "E14 5AB", country: "United Kingdom" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Aisha",
    lastName: "Al-Rashid",
    email: "aisha.alrashid@company.com",
    phone: "+1-212-555-0183",
    designation: "UX Designer",
    department: "Design",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2023-05-22"),
    address: { street: "350 Fifth Avenue", city: "New York", state: "New York", postalCode: "10118", country: "United States" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Luca",
    lastName: "Moretti",
    email: "luca.moretti@company.com",
    phone: "+39-02-555-0129",
    designation: "DevOps Engineer",
    department: "DevOps",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2019-09-03"),
    address: { street: "Via della Moscova 3", city: "Milan", state: "Lombardy", postalCode: "20121", country: "Italy" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Sara",
    lastName: "Lindqvist",
    email: "sara.lindqvist@company.com",
    phone: "+46-8-555-0174",
    designation: "Data Scientist",
    department: "Data",
    employmentType: "Full-Time",
    employmentStatus: "On Leave",
    startDate: new Date("2021-11-15"),
    address: { street: "Kungsgatan 12", city: "Stockholm", state: "Stockholm County", postalCode: "111 35", country: "Sweden" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Marcus",
    lastName: "Johnson",
    email: "marcus.johnson@company.com",
    phone: "+61-2-9555-0163",
    designation: "Engineering Manager",
    department: "Engineering",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2018-04-09"),
    address: { street: "1 Martin Place", city: "Sydney", state: "New South Wales", postalCode: "2000", country: "Australia" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Mei",
    lastName: "Zhang",
    email: "mei.zhang@company.com",
    phone: "+65-6555-0198",
    designation: "QA Automation Lead",
    department: "QA",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2022-08-01"),
    address: { street: "1 Raffles Place", city: "Singapore", state: "", postalCode: "048616", country: "Singapore" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Carlos",
    lastName: "Vega",
    email: "carlos.vega@company.com",
    phone: "+34-91-555-0112",
    designation: "Frontend Engineer",
    department: "Engineering",
    employmentType: "Contract",
    employmentStatus: "Active",
    startDate: new Date("2024-01-08"),
    address: { street: "Gran Vía 28", city: "Madrid", state: "Community of Madrid", postalCode: "28013", country: "Spain" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Fatima",
    lastName: "Okonkwo",
    email: "fatima.okonkwo@company.com",
    phone: "+1-301-555-0144",
    designation: "HR Business Partner",
    department: "HR",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2020-02-17"),
    address: { street: "1600 Pennsylvania Ave NW", city: "Washington", state: "D.C.", postalCode: "20500", country: "United States" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "David",
    lastName: "Kim",
    email: "david.kim@company.com",
    phone: "+82-2-555-0131",
    designation: "Finance Analyst",
    department: "Finance",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2023-03-06"),
    address: { street: "100 Teheran-ro", city: "Seoul", state: "Gangnam-gu", postalCode: "06235", country: "South Korea" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Ananya",
    lastName: "Krishnan",
    email: "ananya.krishnan@company.com",
    phone: "+91-80-555-0166",
    designation: "Intern — Software Engineering",
    department: "Engineering",
    employmentType: "Intern",
    employmentStatus: "Active",
    startDate: new Date("2025-06-01"),
    address: { street: "MG Road 5", city: "Bengaluru", state: "Karnataka", postalCode: "560001", country: "India" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
]);

print("✅  Seeded " + db.employees.countDocuments() + " employees into employee_directory.employees");
