// mongo-init/seed.js
// Runs automatically on first container startup via Docker entrypoint.
// Creates the employees collection and seeds 12 realistic records.

db = db.getSiblingDB("employee_directory");

db.createCollection("employees");
db.employees.createIndex({ email: 1 }, { unique: true });
db.employees.createIndex({ department: 1 });
db.employees.createIndex({ employmentStatus: 1 });
db.employees.createIndex({ lastName: 1, firstName: 1 });
db.employees.createIndex(
  { firstName: "text", lastName: "text", email: "text", designation: "text" },
  { name: "employee_text_search" }
);

const now = new Date();

db.employees.insertMany([
  {
    firstName: "Thava",
    lastName: "Gopal",
    email: "thava.gopal@company.com",
    phone: "+1-416-555-0192",
    designation: "Senior QA Engineer",
    department: "QA",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2022-03-15"),
    address: { street: "123 Innovation Drive", city: "Toronto", state: "Ontario", postalCode: "M5V 3A8", country: "Canada" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Priya",
    lastName: "Ramachandran",
    email: "priya.ramachandran@company.com",
    phone: "+1-604-555-0147",
    designation: "Lead Software Engineer",
    department: "Engineering",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2020-07-01"),
    address: { street: "45 Harbour Centre", city: "Vancouver", state: "British Columbia", postalCode: "V6Z 2E1", country: "Canada" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "James",
    lastName: "O'Sullivan",
    email: "james.osullivan@company.com",
    phone: "+44-20-7946-0958",
    designation: "Product Manager",
    department: "Product",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2021-01-11"),
    address: { street: "10 Canary Wharf", city: "London", state: "England", postalCode: "E14 5AB", country: "United Kingdom" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Aisha",
    lastName: "Al-Rashid",
    email: "aisha.alrashid@company.com",
    phone: "+1-212-555-0183",
    designation: "UX Designer",
    department: "Design",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2023-05-22"),
    address: { street: "350 Fifth Avenue", city: "New York", state: "New York", postalCode: "10118", country: "United States" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Luca",
    lastName: "Moretti",
    email: "luca.moretti@company.com",
    phone: "+39-02-555-0129",
    designation: "DevOps Engineer",
    department: "DevOps",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2019-09-03"),
    address: { street: "Via della Moscova 3", city: "Milan", state: "Lombardy", postalCode: "20121", country: "Italy" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Sara",
    lastName: "Lindqvist",
    email: "sara.lindqvist@company.com",
    phone: "+46-8-555-0174",
    designation: "Data Scientist",
    department: "Data",
    employmentType: "Full-Time",
    employmentStatus: "On Leave",
    startDate: new Date("2021-11-15"),
    address: { street: "Kungsgatan 12", city: "Stockholm", state: "Stockholm County", postalCode: "111 35", country: "Sweden" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Marcus",
    lastName: "Johnson",
    email: "marcus.johnson@company.com",
    phone: "+61-2-9555-0163",
    designation: "Engineering Manager",
    department: "Engineering",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2018-04-09"),
    address: { street: "1 Martin Place", city: "Sydney", state: "New South Wales", postalCode: "2000", country: "Australia" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Mei",
    lastName: "Zhang",
    email: "mei.zhang@company.com",
    phone: "+65-6555-0198",
    designation: "QA Automation Lead",
    department: "QA",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2022-08-01"),
    address: { street: "1 Raffles Place", city: "Singapore", state: "", postalCode: "048616", country: "Singapore" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Carlos",
    lastName: "Vega",
    email: "carlos.vega@company.com",
    phone: "+34-91-555-0112",
    designation: "Frontend Engineer",
    department: "Engineering",
    employmentType: "Contract",
    employmentStatus: "Active",
    startDate: new Date("2024-01-08"),
    address: { street: "Gran Vía 28", city: "Madrid", state: "Community of Madrid", postalCode: "28013", country: "Spain" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Fatima",
    lastName: "Okonkwo",
    email: "fatima.okonkwo@company.com",
    phone: "+1-301-555-0144",
    designation: "HR Business Partner",
    department: "HR",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2020-02-17"),
    address: { street: "1600 Pennsylvania Ave NW", city: "Washington", state: "D.C.", postalCode: "20500", country: "United States" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "David",
    lastName: "Kim",
    email: "david.kim@company.com",
    phone: "+82-2-555-0131",
    designation: "Finance Analyst",
    department: "Finance",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2023-03-06"),
    address: { street: "100 Teheran-ro", city: "Seoul", state: "Gangnam-gu", postalCode: "06235", country: "South Korea" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Ananya",
    lastName: "Krishnan",
    email: "ananya.krishnan@company.com",
    phone: "+91-80-555-0166",
    designation: "Intern — Software Engineering",
    department: "Engineering",
    employmentType: "Intern",
    employmentStatus: "Active",
    startDate: new Date("2025-06-01"),
    address: { street: "MG Road 5", city: "Bengaluru", state: "Karnataka", postalCode: "560001", country: "India" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  // ── Additional employees: ensures >20 total (enables pagination tests) ──────
  // ── and covers all three employmentStatus values ────────────────────────────
  {
    firstName: "Nina",
    lastName: "Petrov",
    email: "nina.petrov@company.com",
    phone: "+7-495-555-0188",
    designation: "Marketing Specialist",
    department: "Marketing",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2021-06-14"),
    address: { street: "Tverskaya 10", city: "Moscow", state: "Moscow Oblast", postalCode: "125009", country: "Russia" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Owen",
    lastName: "Richards",
    email: "owen.richards@company.com",
    phone: "+1-647-555-0201",
    designation: "Sales Executive",
    department: "Sales",
    employmentType: "Full-Time",
    employmentStatus: "Terminated",
    startDate: new Date("2019-11-04"),
    address: { street: "Bay Street 100", city: "Toronto", state: "Ontario", postalCode: "M5J 2S1", country: "Canada" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Elena",
    lastName: "Santos",
    email: "elena.santos@company.com",
    phone: "+55-11-555-0217",
    designation: "Legal Counsel",
    department: "Legal",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2020-09-28"),
    address: { street: "Avenida Paulista 1000", city: "São Paulo", state: "SP", postalCode: "01310-100", country: "Brazil" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Ben",
    lastName: "Turner",
    email: "ben.turner@company.com",
    phone: "+44-161-555-0233",
    designation: "Operations Manager",
    department: "Operations",
    employmentType: "Full-Time",
    employmentStatus: "On Leave",
    startDate: new Date("2018-07-16"),
    address: { street: "Piccadilly 22", city: "Manchester", state: "England", postalCode: "M1 2AN", country: "United Kingdom" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Yuki",
    lastName: "Tanaka",
    email: "yuki.tanaka@company.com",
    phone: "+81-3-555-0249",
    designation: "Frontend Engineer",
    department: "Engineering",
    employmentType: "Contract",
    employmentStatus: "Active",
    startDate: new Date("2023-10-01"),
    address: { street: "Shibuya 2-21", city: "Tokyo", state: "Tokyo", postalCode: "150-0002", country: "Japan" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Grace",
    lastName: "Adeyemi",
    email: "grace.adeyemi@company.com",
    phone: "+234-1-555-0265",
    designation: "HR Coordinator",
    department: "HR",
    employmentType: "Part-Time",
    employmentStatus: "Active",
    startDate: new Date("2022-01-10"),
    address: { street: "Victoria Island 55", city: "Lagos", state: "Lagos State", postalCode: "101241", country: "Nigeria" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Hugo",
    lastName: "Blanc",
    email: "hugo.blanc@company.com",
    phone: "+33-1-555-0281",
    designation: "Product Designer",
    department: "Design",
    employmentType: "Full-Time",
    employmentStatus: "Terminated",
    startDate: new Date("2020-04-20"),
    address: { street: "Rue de Rivoli 1", city: "Paris", state: "Île-de-France", postalCode: "75001", country: "France" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Sofia",
    lastName: "Eriksson",
    email: "sofia.eriksson@company.com",
    phone: "+46-31-555-0297",
    designation: "Data Engineer",
    department: "Data",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2021-03-08"),
    address: { street: "Kungsportsavenyen 5", city: "Gothenburg", state: "Västra Götaland", postalCode: "411 36", country: "Sweden" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Ali",
    lastName: "Hassan",
    email: "ali.hassan@company.com",
    phone: "+971-4-555-0313",
    designation: "Finance Manager",
    department: "Finance",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2019-06-25"),
    address: { street: "Sheikh Zayed Road 10", city: "Dubai", state: "Dubai", postalCode: "00000", country: "United Arab Emirates" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Rachel",
    lastName: "Wong",
    email: "rachel.wong@company.com",
    phone: "+852-555-0329",
    designation: "QA Engineer",
    department: "QA",
    employmentType: "Full-Time",
    employmentStatus: "Active",
    startDate: new Date("2023-02-13"),
    address: { street: "Causeway Bay 8", city: "Hong Kong", state: "", postalCode: "000000", country: "Hong Kong" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Ivan",
    lastName: "Novak",
    email: "ivan.novak@company.com",
    phone: "+420-2-555-0345",
    designation: "Backend Engineer",
    department: "Engineering",
    employmentType: "Full-Time",
    employmentStatus: "On Leave",
    startDate: new Date("2020-11-30"),
    address: { street: "Wenceslas Square 1", city: "Prague", state: "Bohemia", postalCode: "110 00", country: "Czech Republic" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
  {
    firstName: "Mia",
    lastName: "Johansson",
    email: "mia.johansson@company.com",
    phone: "+46-40-555-0361",
    designation: "UX Researcher",
    department: "Design",
    employmentType: "Part-Time",
    employmentStatus: "Active",
    startDate: new Date("2024-03-18"),
    address: { street: "Stortorget 1", city: "Malmö", state: "Skåne", postalCode: "211 22", country: "Sweden" },
    avatarUrl: "",
    createdAt: now, updatedAt: now,
  },
]);

print("✅  Seeded " + db.employees.countDocuments() + " employees into employee_directory.employees");
